// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhjEs-KgngB_-kjMdZ5y4265tyFUwXo40',
    appId: '1:492295026226:web:6918b5f6af5e32311aee2b',
    messagingSenderId: '492295026226',
    projectId: 'turfbookingapplicationforadmin',
    authDomain: 'turfbookingapplicationforadmin.firebaseapp.com',
    storageBucket: 'turfbookingapplicationforadmin.appspot.com',
    measurementId: 'G-LEGYKKXTF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPcpQeqa7DrCT4j_knoAe5X0lO-oKJGxQ',
    appId: '1:492295026226:android:abb92d015b61bd831aee2b',
    messagingSenderId: '492295026226',
    projectId: 'turfbookingapplicationforadmin',
    storageBucket: 'turfbookingapplicationforadmin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMjKukNlumosUZp0wjywGdVNV-4FePvH0',
    appId: '1:492295026226:ios:643624eb539d10d21aee2b',
    messagingSenderId: '492295026226',
    projectId: 'turfbookingapplicationforadmin',
    storageBucket: 'turfbookingapplicationforadmin.appspot.com',
    iosBundleId: 'fathima.turfBookingApplicationForAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMjKukNlumosUZp0wjywGdVNV-4FePvH0',
    appId: '1:492295026226:ios:ea3969c7c85e17191aee2b',
    messagingSenderId: '492295026226',
    projectId: 'turfbookingapplicationforadmin',
    storageBucket: 'turfbookingapplicationforadmin.appspot.com',
    iosBundleId: 'fathima.turfBookingApplicationForAdmin.RunnerTests',
  );
}
